# Generated by Django 2.2.6 on 2020-01-16 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200117_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='msg',
            field=models.CharField(default='Error', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 20, 26, 11, 789386, tzinfo=utc)),
        ),
    ]
