# Generated by Django 2.2.6 on 2020-01-16 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20200117_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 20, 34, 24, 195449, tzinfo=utc)),
        ),
    ]
