# Generated by Django 2.2.6 on 2020-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='station1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station10',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station11',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station12',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station13',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station14',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station15',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station16',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station17',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station18',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station19',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station20',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station3',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station4',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station5',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station6',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station7',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station8',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='station9',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
