# Generated by Django 2.2.6 on 2020-01-11 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200111_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='train_no',
        ),
        migrations.AlterField(
            model_name='train',
            name='train_from_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 6, 48, 41, 956873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_to_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 6, 48, 41, 956873, tzinfo=utc)),
        ),
    ]
