# Generated by Django 2.2.6 on 2020-01-11 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20200111_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='phone',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='train_from_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 7, 11, 18, 314807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_to_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 7, 11, 18, 314807, tzinfo=utc)),
        ),
    ]
