# Generated by Django 2.2.6 on 2020-01-11 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200111_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='Jabalpur', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='train_from_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 10, 28, 37, 994528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_to_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 11, 10, 28, 37, 994528, tzinfo=utc)),
        ),
    ]
