# Generated by Django 2.2.6 on 2020-01-15 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20200115_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='tarin_days',
            new_name='train_days',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='tarin_live_station',
            new_name='train_live_station',
        ),
        migrations.AlterField(
            model_name='train',
            name='train_from_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 15, 7, 30, 57, 491442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_to_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 15, 7, 30, 57, 491442, tzinfo=utc)),
        ),
    ]
