# Generated by Django 2.2.6 on 2020-01-15 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20200115_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_from_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 15, 16, 5, 35, 688500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_to_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 15, 16, 5, 35, 688500, tzinfo=utc)),
        ),
    ]
