# Generated by Django 2.2.6 on 2020-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcel', '0003_parcel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('ShippingSoon', 'ShippingSoon'), ('Shipped', 'Shipped'), ('OutForDelivery', 'OutForDelivery'), ('Delivered', 'Delivered')], default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
