# Generated by Django 2.2.6 on 2020-01-11 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0002_auto_20200110_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 6, 40, 46, 115505, tzinfo=utc)),
        ),
    ]
