# Generated by Django 2.2.6 on 2020-01-11 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0003_auto_20200111_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 6, 48, 41, 959374, tzinfo=utc)),
        ),
    ]
