# Generated by Django 2.2.6 on 2020-01-11 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0004_auto_20200111_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 7, 11, 18, 317307, tzinfo=utc)),
        ),
    ]
