# Generated by Django 2.2.6 on 2020-01-11 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0005_auto_20200111_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 10, 28, 37, 997029, tzinfo=utc)),
        ),
    ]
