# Generated by Django 2.2.6 on 2020-01-14 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0006_auto_20200111_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 14, 0, 9, 527588, tzinfo=utc)),
        ),
    ]
