# Generated by Django 2.2.6 on 2020-01-15 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0007_auto_20200114_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 6, 50, 23, 665099, tzinfo=utc)),
        ),
    ]
