# Generated by Django 2.2.6 on 2020-01-15 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0009_auto_20200115_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 7, 30, 57, 493443, tzinfo=utc)),
        ),
    ]
