# Generated by Django 2.2.6 on 2020-01-16 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0012_auto_20200115_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 8, 41, 20, 373523, tzinfo=utc)),
        ),
    ]
