# Generated by Django 2.2.6 on 2020-01-16 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LiveTracking', '0014_auto_20200116_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 20, 3, 48, 768328, tzinfo=utc)),
        ),
    ]
